---
# defaults file for wordpress
wordpress_archive_source: 'https://wordpress.org/latest.zip'
wordpress_mysql_db_name: 'wordpress'
wordpress_mysql_db_user: 'wordpress'
wordpress_mysql_db_passwdord: 'secret'
wordpress_mysql_login_user: 'root'
wordpress_mysql_login_password: ''
wordpress_user: 'www-data'
wordpress_group: 'www-data'
wordpress_mysql_host: 'localhost'
wordpress_nginx_handler_name: 'restart nginx service'