---
# tasks file for mysql
- name: 'install mysql required packages'
  apt:
    name: 'mysql-server'
    state: 'present'
    update_cache: true
  become: true

- name: 'Install python3-pip '
  apt:
    name: 'python3-pip'
    state: 'present'
  become: true

- name: 'Required python-mysql module'
  pip:
    name: 'PyMySQL'
    state: 'present'
  become: true

- name: Set mysql root password
  mysql_user:
    name: 'root'
    password: '{{mysql_root_password}}'
    login_unix_socket: '{{mysql_unix_socket_path}}'
    check_implicit_admin: yes
    login_user: 'root'
    login_password: '{{mysql_root_password}}'
  become: true

- name: 'create none-root DB user'
  mysql_user:  
    name: '{{mysql_user }}'
    password: '{{mysql_user_passwd}}'
    update_password: 'on_create'
    priv: '{{mysql_user_priv}}'
    login_user: root
    #login_unix_socket: '/var/run/mysqld/mysqld.sock'
    login_password: '{{mysql_root_password}}'
    #state: 'present'
  become: true  

- name: 'Mysql service is running'
  service:
    name: 'mysql'
    state: 'started'
    enabled: true
  become: true