---
- hosts: 'webservers'
  remote_user: 'ubuntu'
  vars_files:
         - './group_value/variables.txt'
  tasks:
   - name: 'install required packages'
     apt:
       name: 
           - 'nginx'
           - 'php-fpm'
           - 'php-mysql'
           - 'mysql-server'
           - 'python3-pip'
             #        - 'python3-pymysql'
       state: 'present'
       update_cache: true
     become: true
   - name: 'Download and extract Wordpress files'
     unarchive:
       src: 'https://wordpress.org/latest.zip'
       dest: '/var/www/html/'
       owner: 'www-data'
       group: 'www-data'
       remote_src: true 
     become: true
   - name: 'Required python-mysql module'
     pip:
       name: 'PyMySQL'
       state: 'present'
     become: 'true'

   - name: 'Set Mysql root password'
     mysql_user: 
        name: 'root' 
        password: "{{ mysql_root_pass }}"
        login_user: 'root'
        login_password: "{{ mysql_root_pass }}"
        check_implicit_admin: 'yes'
        priv: "*.*:ALL,GRANT"
        login_unix_socket: '/var/run/mysqld/mysqld.sock'
     become: 'yes'
   - name: 'create user for wordpress'
     community.mysql.mysql_user:  
       name: 'wordpress1_user'
       login_password: '{{wordpress_password}}'
       priv: '*.*:ALL,GRANT'
       login_user: 'root'
       ogin_password: '{{mysql_root_pass}}'
       state: 'present'
     become: true
   - name: 'create wordpress db'
     mysql_db:
             name: 'wordpress1_db'
             state: 'present'
             login_user: 'root'
             login_password: "{{mysql_root_pass}}"
     become: 'yes'
   - name: 'Config file transfere'
     template:
             src: './wp-config.php'
             dest: '/var/www/html/wordpress/wp-config.php'
     become: 'yes'

   - name: 'wordpress nginx config file'
     copy:
             src: './wordpress'
             dest: '/etc/nginx/sites-available/wordpress'
     become: 'yes'
   
   - name: 'Create symlink  for wordpress nginx config'
     file:
       src: '/etc/nginx/sites-available/wordpress'
       dest: '/etc/nginx/sites-avilable/wordpress'
       state: 'link'
     become: 'true'
     handlers:
     - name: 'Restart Nginx'
       become: true
       service:
         name: 'nginx'
         state: 'restarted'

