---
# defaults file for mysql
mysql_version: '8.0.23'
mysql_root_password: 'secret'
mysql_unix_socket_path: '/var/run/mysqld/mysqld.sock'

mysql_user: 'user'
mysql_user_passwd: 'secret'
mysql_user_priv: '*.*:ALL'